## defineAsyncComponent

> 官方定义：创建一个只有在需要时才会加载的异步组件。
>
> 对于基本用法，`defineAsyncComponent` 可以接受一个返回 `Promise` 的工厂函数。Promise 的 `resolve` 回调应该在服务端返回组件定义后被调用。你也可以调用 `reject(reason)` 来表示加载失败
>
> 对于高阶用法，`defineAsyncComponent` 可以接受一个对象：

* 一般用法

```ts
import { createApp, defineAsyncComponent } from 'vue'

createApp({
  // ...
  components: {
    AsyncComponent: defineAsyncComponent(() =>
      import('./components/AsyncComponent.vue')
    )
  }
})
```

* 高级用法

```ts
import { defineAsyncComponent } from 'vue'

const AsyncComp = defineAsyncComponent({
  // 工厂函数
  loader: () => import('./Foo.vue')
  // 加载异步组件时要使用的组件
  loadingComponent: LoadingComponent,
  // 加载失败时要使用的组件
  errorComponent: ErrorComponent,
  // 在显示 loadingComponent 之前的延迟 | 默认值：200（单位 ms）
  delay: 200,
  // 如果提供了 timeout ，并且加载组件的时间超过了设定值，将显示错误组件
  // 默认值：Infinity（即永不超时，单位 ms）
  timeout: 3000,
  // 定义组件是否可挂起 | 默认值：true
  suspensible: false,
  /**
   *
   * @param {*} error 错误信息对象
   * @param {*} retry 一个函数，用于指示当 promise 加载器 reject 时，加载器是否应该重试
   * @param {*} fail  一个函数，指示加载程序结束退出
   * @param {*} attempts 允许的最大重试次数
   */
  onError(error, retry, fail, attempts) {
    if (error.message.match(/fetch/) && attempts <= 3) {
      // 请求发生错误时重试，最多可尝试 3 次
      retry()
    } else {
      // 注意，retry/fail 就像 promise 的 resolve/reject 一样：
      // 必须调用其中一个才能继续错误处理。
      fail()
    }
  }
})
```

* 源🐴（套！！！！）

```ts
export function defineAsyncComponent<
  T extends Component = { new (): ComponentPublicInstance }
>(source: AsyncComponentLoader<T> | AsyncComponentOptions<T>): T {
  if (isFunction(source)) {
    source = { loader: source }
  }

  /*
	我们高级用法时传入的参数
  */
  const {
    loader,
    loadingComponent,
    errorComponent,
    delay = 200,
    timeout, // undefined = never times out
    suspensible = true,
    onError: userOnError
  } = source 

  let pendingRequest: Promise<ConcreteComponent> | null = null
  let resolvedComp: ConcreteComponent | undefined

  let retries = 0
  const retry = () => { // 重新尝试load得到组件内容
    retries++
    pendingRequest = null
    return load()
  }

  const load = (): Promise<ConcreteComponent> => {
    let thisRequest: Promise<ConcreteComponent>
    return (
      // 如果pendingRequest 存在就return，否则实行loader
      pendingRequest ||
      (thisRequest = pendingRequest = loader()
       .catch(err => { // 捕获我们的异步组件是否出错了
          err = err instanceof Error ? err : new Error(String(err))
          if (userOnError) {
            // 失败捕获的钩子，我们可以调用
            return new Promise((resolve, reject) => {
              const userRetry = () => resolve(retry()) // 重试加载组件
              const userFail = () => reject(err)
              userOnError(err, userRetry, userFail, retries + 1)
            })
          } else {
            throw err
          }
        })
       // 我们的异步组件很奥利给，加载成功了
       .then((comp: any) => {
          // 我们组件是异步的，初次加载是'pendding'中，当加载成功进入到此行代🐴的时候,
          // loader是我们传入的() => import('./Modal.vue')
          /*
          emmmmm实在看不懂这个判断
          1. 第一次进入是thisRequest === pendingRequest，为Promise {<pending>}
          2. 举例吧，有理解的，+Q1392558812指正一下
          3. 首先第一次执行thisRequest与pendingRequest都为Promise {<pending>}，promise为pending
          4. 那如何进入这个判断？：
          		1. pendingRequest为null
          		2. loader()加载成功
          		3. thisRequest pendingRequest都有值
          		推测： 那只能是重新执行load()才可能有这种情况，那么，这个判断我猜是为了处理“retry()这个函数第一次没加载成功后来加载成功了”造成的					thisRequest与pendingRequest不同步问题
          		测试demo: 
          				 let emmm = (str) => {
                            let pendingRequest = null
                            const loader = (str) => {
                              return new Promise((resolve,reject) => {
                                setTimeout(() => {
                                  if (new Date().getTime() % 2) {
                                    resolve(str)
                                  } else {
                                    reject(str)
                                  }
                                },1000)
                              })
                            }
                            const load = (str) => {
                              let thisRequest
                              return (
                                pendingRequest || (thisRequest = pendingRequest = loader(str)
                                .catch(res => {
                                  pendingRequest = null
                                  console.error('~~~~~~~~~~~')
                                  return load(str)
                                })
                                  .then(res => {
                                    if (thisRequest !== pendingRequest && pendingRequest) {
                                      debugger
                                      console.log('套！！！！！终于进这个判断了',thisRequest, pendingRequest)
                                      return pendingRequest
                                    }
                                    console.log('res', res, pendingRequest)
                                    return res
                                  })
                                ))
                            }
                            console.log(load(str))
                            setTimeout(() => {
                              console.log('pendingRequest', pendingRequest,load('操作起来'))
                            },3000)
                            return {
                              load
                            }
                          }
                          emmm('emmm').load('老八秘制小汉堡')
                          setTimeout(() => {
                            emmm('太捞了啊！！！').load('加个🍋喜滋滋')
                          }, 5000)
          */
          if (thisRequest !== pendingRequest && pendingRequest) {
            return pendingRequest
          }
          if (__DEV__ && !comp) {
            warn(
              `Async component loader resolved to undefined. ` +
                `If you are using retry(), make sure to return its return value.`
            )
          }
          // interop module default
          if (
            comp &&
            (comp.__esModule || comp[Symbol.toStringTag] === 'Module')
          ) {
            comp = comp.default
          }
          // 异步加载的并不是一个组件或者纯函数
          if (__DEV__ && comp && !isObject(comp) && !isFunction(comp)) {
            throw new Error(`Invalid async component load result: ${comp}`)
          }
          resolvedComp = comp
          return comp 
          // 这里return了，那么外层即“thisRequest = pendingRequest = loader()”中的pendingRequest得到值了跟新
        }))
    )
  }

  return defineComponent({
    __asyncLoader: load,
    name: 'AsyncComponentWrapper',
    setup() {
      const instance = currentInstance!
      // already resolved
      if (resolvedComp) {
        return () => createInnerComp(resolvedComp!, instance)
      }
      const onError = (err: Error) => {
        pendingRequest = null
        handleError(
          err,
          instance,
          ErrorCodes.ASYNC_COMPONENT_LOADER,
          !errorComponent /* do not throw in dev if user provided error component */
        )
      }

      // suspense-controlled or SSR.  suspense与ssr场景emmmmm
      if (
        (__FEATURE_SUSPENSE__ && suspensible && instance.suspense) ||
        (__NODE_JS__ && isInSSRComponentSetup)
      ) { // 父组件是一个 suspense 那么只返回promise结果 其余的控制交给 suspense 处理
        return load()
          .then(comp => {
            return () => createInnerComp(comp, instance)
          })
          .catch(err => {
            onError(err)
            return () =>
              errorComponent
                ? createVNode(errorComponent as ConcreteComponent, {
                    error: err
                  })
                : null
          })
      }

      const loaded = ref(false)
      const error = ref()
      const delayed = ref(!!delay)
      if (delay) {
        setTimeout(() => {
          delayed.value = false
        }, delay)
      }
      if (timeout != null) {
        setTimeout(() => { // 处理加载超时
          if (!loaded.value && !error.value) {
            const err = new Error(
              `Async component timed out after ${timeout}ms.`
            )
            onError(err)
            error.value = err
          }
        }, timeout)
      }

      load() // 加载成功改变加载状态
        .then(() => {
          loaded.value = true
        })
        .catch(err => {
          onError(err)
          error.value = err
        })
	  // resolvedComp为异步导入的组件 errorComponent为加载失败的组件  loadingComponent加载中的组件
      // loaded.value加载成功   error.value加载失败
      // !delayed.value不在延迟n秒出现加载动画时间内且有加载动画组件
      return () => { 
        if (loaded.value && resolvedComp) {
          return createInnerComp(resolvedComp, instance)
        } else if (error.value && errorComponent) {
          return createVNode(errorComponent as ConcreteComponent, {
            error: error.value
          })
        } else if (loadingComponent && !delayed.value) {
          return createVNode(loadingComponent as ConcreteComponent)
        }
      }
    }
  }) as any
}
```

